### ISSUE TITLE
Any plans on making this work with JWT instead of user cookies?

### ISSUE THREAD

**Issue by bo-oz** [mclintprojects/actioncable-vue#10]
I found a fork on Github that adds functionality to make use of JWT to connect to Rails ActionCable. Any plans on incorporating this into the codebase and/or create your own functionality?

This is the repo that embedded JWT: https://github.com/requnix/actioncable-vue-jwt#readme

Thanks!

**Comment by mclintprojects** [comment]
I'll add that over the weekend.

**Comment by bo-oz** [comment]
Cool, that would be really nice! I ended up solving it by disabling auto-connect and resetting the `_connectionUrl` just before I create the subscription. I'm now passing the JWT token as a GET parameter, but that just feels a bit insecure. It would be great to have a more rigid way, by setting custom header or using a POST variable (is that even possible with WS?).

Let me know if there is anything I can do to help. Although JS isn't my primary domain, I know a lot about RoR though.

**Comment by mclintprojects** [comment]
Just added this. Kindly update to v1.7.0 and let me know how it goes.

**Comment by Buk1m** [comment]
I don't believe what you did is working. 
[Forked version](https://github.com/requnix/actioncable-vue-jwt/blob/master/src/cable.js#L1) has overridden `actioncable` dependency. 
He added token variable to consumer [here](https://github.com/requnix/actioncable-vue-jwt/blob/master/src/actioncable.js#L502)

and then appending it [here](https://github.com/requnix/actioncable-vue-jwt/blob/master/src/actioncable.js#L199)

Original [actioncable@5.2](https://github.com/rails/rails/blob/5-2-stable/actioncable/app/assets/javascripts/action_cable.coffee.erb#L10) version form rails repository doesn't have `createConsumer` method which uses 2 arguments.

**Comment by mclintprojects** [comment]
Thanks, @Buk1m! I'll look into this.

**Comment by Buk1m** [comment]
According to [actioncable documentation](https://guides.rubyonrails.org/action_cable_overview.html#connect-consumer)
One can already pass a function instead of string to dynamically resolve url. So i think that you only need to change validation for `connectionUrl` to string or function - 
[my fork](https://github.com/Buk1m/actioncable-vue/commit/a74fedfee4038fb23fd236ee921bbbd46faab1b0#diff-990bacc9bbef556c611b24e5e7c3b8efR166)

I didn't test this yet.

**Comment by mclintprojects** [comment]
Thanks for helping out. I'll check that your patch works and if it does I'll merge it in.

**Comment by mclintprojects** [comment]
Should be all good now. Thanks again, @Buk1m!
