### ISSUE TITLE
Nuxtjs Typescript

### ISSUE THREAD

**Issue by tititoof** [mclintprojects/actioncable-vue#14]
**Describe the bug**
No logger and no channel functions used in Component

**To Reproduce**
Using NuxtJS with Typescript 
My components with 'vue-property-decorator'

**Expected behaviour**
I've installed actioncable-vue in my nuxtjs app (frontend and backend separated)
Like in description, I configure actioncable-vue with nuxtjs 
In my component, I create a subscription to a "Contact channel"
But when i want to use connected or received functions, nothing append and no logs ... 
How to use actioncable-vue with typescript ? 

**Screenshots**
Component :
![actioncable-vue-code](https://user-images.githubusercontent.com/1619046/79036953-7f271000-7bcd-11ea-8b8d-33c26f4a9ed1.png)

NuxtJS configuration :
![nuxtjs-conf](https://user-images.githubusercontent.com/1619046/79036978-b2699f00-7bcd-11ea-8759-54ab99b07178.png)

websocket :
![network-cable](https://user-images.githubusercontent.com/1619046/79037012-ee9cff80-7bcd-11ea-930e-79edae06907e.png)

RoR logs : 
![backend](https://user-images.githubusercontent.com/1619046/79037038-286e0600-7bce-11ea-904a-9272f1b3b273.png)

**Plugin version (please complete the following information):**
actioncable-vue : 2.0.2
RoR 6.0.2

**Comment by mclintprojects** [comment]
Hi @tititoof! Did you correctly follow the setup instructions in the README? Please double-check and if you're still having the issue we can hop on a Zoom call and I'll help investigate.

All my tests are passing so I don't think I broke something with my latest release. It might be your setup either client or server-side.

**Comment by tititoof** [comment]
Hi @mclintprojects , 
I will check my settings
Thanks for helping ;)

**Comment by tititoof** [comment]
That's me sorry for disturb :)
