### ISSUE TITLE
Nuxt.js + actioncable-vue

### ISSUE THREAD

**Issue by z0dz0dz0dz0d** [mclintprojects/actioncable-vue#19]
**Describe the bug**
I'm having an issue getting actioncable-vue to work with Nuxt.js As for my Nuxt.js setup, I'm using it with Typescript support. I followed the steps described specifically for Nuxt.js (updating nuxt.config.js & adding plugin), however, when I start the application, the issue I get says `You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.`

**To Reproduce**
Steps to reproduce the behaviour:
1. Create Nuxt.js project with Typescript support
2. Update `nuxt.config.js` and add plugin as described in `README.md` file
3. Start the application
4. Error appears

**Expected behaviour**
Application runs without the error

**Screenshots**
![Screen Shot 2020-04-24 at 10 10 13 AM](https://user-images.githubusercontent.com/30198951/80190751-100dda80-8615-11ea-9da5-f7057495e858.png)

**Plugin version (please complete the following information):**
- nuxt (2.12.2)
- actioncable-vue (2.1.0)

**Additional context**
None

**Comment by mclintprojects** [comment]
Ahh. Interesting. Give me a few minutes to read up on loaders. I'll publish a new version that you can test in your project and let me know if the bug is fixed.

**Comment by mclintprojects** [comment]
@z0dz0dz0dz0d Please try this [build](https://github.com/mclintprojects/actioncable-vue/blob/nuxt-fix/dist/actioncablevue.js) and let me know if it works.

**Comment by z0dz0dz0dz0d** [comment]
@mclintprojects thank you very much for such a quick answer!

Unfortunately, the fix didn't help - I've replaced content of `actioncablevue.js` and `rollup.config.js`.

**Comment by mclintprojects** [comment]
@z0dz0dz0dz0d Kindly try [this](https://github.com/mclintprojects/actioncable-vue/blob/nuxt-fix/dist/actioncablevue.js) too.

**Comment by mclintprojects** [comment]
I just created a test Nuxt project locally and that build works. I'll publish a new build to NPM now. Thanks for your help!

**Comment by z0dz0dz0dz0d** [comment]
I just tried pulling the latest package (confirmed its 2.1.1) and it didn't work. I've also tried to manually update built, that also didn't work.

**Comment by mclintprojects** [comment]
That's really weird because I created a brand new Nuxt project and tested that it works correctly.

Is there anything non-default about your Nuxt project?

**Comment by z0dz0dz0dz0d** [comment]
Nothing particular. It uses Vuetify and Typescript.

**Comment by mclintprojects** [comment]
Whew! Finally fixed this. Please update to v2.1.2.
