### ISSUE TITLE
I can not access to 'this' context in the channelName computed method.

### ISSUE THREAD

**Issue by Jinara** [mclintprojects/actioncable-vue#21]
I can not access to 'this' context in the channelName computed method.

**To Reproduce**
Steps to reproduce the behaviour:
I have a VueJS app, I added the follow in my  main.js file

```
Vue.use(ActionCableVue, {
  debug: true,
  debugLevel: 'error',
  connectionUrl: `ws://${process.env.VUE_APP_BASE_BACKEND_DOMAIN}/cable?token=${token}`,
  connectImmediately: true,
});
```
Then I created a component like this:
```
  export default {
    name: 'MyComponent',

    props: {
      room: {
        type: String,
        default: ""
      }
    },

    data() {
      return {
        state: 'none'
      }
    },

    channels: {
      computed: [{
        channelName() {
          return this.room
        },
        connected() {
          console.log("Connected")
        },
        rejected() {
          console.log("Connection Rejected")
        },
        received(data) {
          this.state = data["state"]
        }
      }]
    },

    mounted() {
      this.$cable.subscribe({
        channel: 'MyChannel',
        room: this.room
      })
    }
  }

```

When I try to get `this.room` it return 'Undefined'

**Expected behaviour**
Like the example 3, I would like to pass `this.room` like channel name.

I'm using the las version: 2.1.2

**Additional context**
I would like to render this component many times with different rooms on the same page when I render this component one time, it works properly.

**Comment by mclintprojects** [comment]
Hi @Jinara! I just fixed this. Kindly update to v2.1.3.

**Comment by Petercopter** [comment]
@mclintprojects Similar problem here. I've got a component in a loop, and `this.id` always returns the value of the last item in the loop. It seems like the channels method is not properly maintaining local context.

```
channels: {
    LikeChannel: {
      connected() {
        console.log(this.id)
      }
    }
  }
```

```
  mounted() {
    this.$cable.subscribe({
      channel: 'LikeChannel',
      id: this.id
    })
  },

**Comment by mclintprojects** [comment]
Ahh. It seems like I did not properly understand this issue. I do now and I'll look into publishing a fix as soon as I can.

**Comment by Petercopter** [comment]
@mclintprojects you are the freaking man. Thank you so much, it works great otherwise!

**Comment by mclintprojects** [comment]
@Petercopter Kindly use this [build](https://github.com/mclintprojects/actioncable-vue/blob/multi-cc/dist/actioncablevue.js) directly in your project and let me if it fixes you and @Jinara's issue.

**Comment by Petercopter** [comment]
@mclintprojects Yep! That did the trick. `this` is now referring to the correct context while in a loop. Thanks for the quick turnaround.

**Comment by mclintprojects** [comment]
Alright, thanks! I'll publish a patch to NPM in a few.

**Comment by Petercopter** [comment]
@mclintprojects `2.1.4` did the trick, thank you!

**Comment by vokshirg** [comment]
"actioncable-vue": "^2.3.2",
**this** is undefined
