### ISSUE TITLE
Question: A way to pass JWT not in a query params?

### ISSUE THREAD

**Issue by lennoximus** [mclintprojects/actioncable-vue#24]
Hello there, creators. Awesome package, you've made, love it.
 I was just wondering if there is any way to send JWT, not in the server query, but either in headers or by cookies? Also, was looking through the sources and somewhat related [issues](https://github.com/mclintprojects/actioncable-vue/issues/10), though found nothing useful, unfortunately. Any leads? Maybe I'm missing something or not understanding subject correctly.

Thanks in advance for your work and attention.

**Comment by mclintprojects** [comment]
Hi @lennoximus. I don't think this is possible. This package uses actioncable.js under the hood and from this [StackOverflow](https://stackoverflow.com/questions/35501931/send-auth-token-for-authentication-to-actioncable) answer it doesn't seem possible.

**Comment by phlegx** [comment]
Hi! What about this strategy?

https://www.npmjs.com/package/actioncable-js-jwt

Looks promising! What do you think @mclintprojects @lennoximus?
