### ISSUE TITLE
Property '$cable' does not exist on type 'ConversationComponent'.

### ISSUE THREAD

**Issue by RealRobin-com** [mclintprojects/actioncable-vue#27]
**Describe the bug**
There is not a typescript definition for this library. While the code works, typescript will show errors in the build

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Vue project with typescript enabled
2. Install and setup actioncable-vue
3. reference `this.$cables` in a component

**Expected behaviour**
* no error message
* code completion

**Screenshots**

**Plugin version (please complete the following information):**
2.2.0

**Additional context**
cli output
```
 101:10 Property '$cable' does not exist on type 'ConversationComponent'.
     99 |
    100 |   async mounted() {
  > 101 |     this.$cable.subscribe({
        |          ^
    102 |       channel: "ConversationChannel",
    103 |       id: this.id
    104 |     });
Version: typescript 3.8.3
```

**Comment by mclintprojects** [comment]
Kindly share more code (ideally of the whole component). I think the issue [here](https://stackoverflow.com/questions/53335662/use-plugin-given-vue-constructor-for-component-inheritance-with-vue-component-cl) might be similar to yours.

**Comment by mclintprojects** [comment]
@RealRobin-com I don't know enough Typescript. Can you help contribute the types for the package?

**Comment by mclintprojects** [comment]
You can take inspiration from this project > https://github.com/probil/vue-socket.io-extended/tree/master/types

**Comment by RealRobin-com** [comment]
We can submit a PR
