### ISSUE TITLE
Actioncable 6.0 support

### ISSUE THREAD

**Issue by rokumatsumoto** [mclintprojects/actioncable-vue#3]
In the future version of this library, will we see Actioncable 6.0 support? 

Thanks!

**Comment by mclintprojects** [comment]
Hi @rokumatsumoto ! What changed in ActionCable 6.0 that isn't currently supported by this library?

**Comment by rokumatsumoto** [comment]
Hi @mclintprojects. 
The new rails app comes with `@rails/actioncable 6.0.0` version. I can't answer your question but your tests should be working when `actioncable 5.2.2` dependency upgraded to  `@rails/actioncable 6.0.0` with a new version.

Rails 6.0 Action Cable release notes
https://edgeguides.rubyonrails.org/6_0_release_notes.html#action-cable

Action Cable 6.0 release notes (detailed)
https://github.com/rails/rails/blob/6-0-stable/actioncable/CHANGELOG.md

**Comment by mclintprojects** [comment]
Ahh, I see. Thank you. I'll update and publish a new version now.

**Comment by brendon** [comment]
Hi there, I was wondering if you could release a new version with actionable 6 as the dependency?

https://github.com/rails/rails/blob/v6.0.2.2/actioncable/CHANGELOG.md

```
	"dependencies": {
		"actioncable": "^6.0.0"
	},
```

The only change that might need to be made is from the CHANGELOG:

> The ActionCable javascript package has been converted from CoffeeScript to ES2015, and we now publish the source code in the npm distribution.
> 
> This allows ActionCable users to depend on the javascript source code rather than the compiled code, which can produce smaller javascript bundles.
> 
> This change includes some breaking changes to optional parts of the ActionCable javascript API:
> 
> Configuration of the WebSocket adapter and logger adapter have been moved from properties of ActionCable to properties of ActionCable.adapters. If you are currently configuring these adapters you will need to make these changes when upgrading:
> 
> -    ActionCable.WebSocket = MyWebSocket
> +    ActionCable.adapters.WebSocket = MyWebSocket
> -    ActionCable.logger = myLogger
> +    ActionCable.adapters.logger = myLogger
> The ActionCable.startDebugging() and ActionCable.stopDebugging() methods have been removed and replaced with the property ActionCable.logger.enabled. If you are currently using these methods you will need to make these changes when upgrading:
> 
> -    ActionCable.startDebugging()
> +    ActionCable.logger.enabled = true
> -    ActionCable.stopDebugging()
> +    ActionCable.logger.enabled = false

**Comment by mclintprojects** [comment]
Yikes. I thought I updated it. Turns out I didn't and I just realized why. I'll update now.

**Comment by brendon** [comment]
Thanks @mclintprojects, looking forward to it! :D

**Comment by mclintprojects** [comment]
@brendon @rokumatsumoto Hi guys! I just upgrade the library to 6.0.0, tests are passing and everything looks good but I was hoping you guys could try it out and confirm that idea everything looks good before I merge to master and publish to NPM.

Just download [this](https://github.com/mclintprojects/actioncable-vue/blob/mc/upgrade/dist/actioncablevue.js) and add it to your projects and let me know if anything is broken.

**Comment by brendon** [comment]
Hi @mclintprojects, I've just tried this out and it works well as far as my use case goes :)
