### ISSUE TITLE
TypeError : cannot read property 'received' of undefined

### ISSUE THREAD

**Issue by laurentmahieu** [mclintprojects/actioncable-vue#34]
TypeError : cannot read property 'received' of undefined

**Expected behaviour**
Hi, I join the project recently. We are using actioncable-vue, we received message. Everything seems to be ok. 
But in our sentry we get an error ( screenshot. ). 

According to Sentry, the problem should come from `node_modules/actioncable-vue/dist/actioncablevue.js`. 
Someone got this problem? 
someone could explain, where could problem come from ? 

**Screenshots**
<img width="683" alt="Capture d’écran 2020-09-29 à 12 23 28" src="https://user-images.githubusercontent.com/53560497/94546876-c32ad180-024e-11eb-81bc-ca33911bf237.png">

**Comment by mclintprojects** [comment]
That error looks like it's trying to find a subscription so it can call the `received` callback on it but in your case, the subscription doesn't seem to exist.

Kindly share code snippets of your `channels` object and you subscribing and I just might be able to spot the problem.

**Comment by laurentmahieu** [comment]
Thank you !
I have several more or less complex channels, I don't know which one is problematic.
here is an example of a simple:
`channels: {
    RoomChannel: {
      connected() {},
      rejected() {},
      received(data) {
        if (data.hasOwnProperty("content")) {
          this.messages.push(data);
          this.scollToBottom();
        }
      },
      disconnected() {}
    }
  },`

 And here my subscribing: 
`ActionCableConnect() {
      let urlConnect = `${
        config.ws_url
      }cable?Okta-Access-Token=${getAccessToken()}&Okta-Id-Token=${getIdToken()}`;
      Vue.use(ActionCableVue, {
        debug: config.websocket_debug,
        debugLevel: "all",
        connectionUrl: urlConnect,
        connectImmediately: true
      });
    },`

**Comment by mclintprojects** [comment]
I think you should look through your subscriptions. You seem to be making at least one incorrect subscription.

**Comment by vijaypemmaraju** [comment]
For anyone who runs into this in the future, this is why we were seeing it:
1. Our backend was upgraded to rails 6, but our client js library was still on `actioncable@5.x`
2. Users not signed into our app were receiving a message to the client that looks like this `{"type":"disconnect","reason":"unauthorized","reconnect":false}`
3. This wasn't not being handled correctly by the 5.x version of the library and hence throwing this error.

We were able to resolve the issue by upgrading to `@rails/actioncable@6.x`
