### ISSUE TITLE
Issue on ios using capacitor 

### ISSUE THREAD

**Issue by kairos0ne** [mclintprojects/actioncable-vue#35]
I'm experiencing an issue on ios deployed with capacitor.

The app connects great through all the browsers but not when I deploy on ios with capacitor. Oddly it works fine with android on google play. 

I was wondering if you had any thoughts on that.

**Comment by mclintprojects** [comment]
Hmm. I have no idea what might be going wrong here. Does it at least throw an error?

**Comment by kairos0ne** [comment]
No actually looking into with my team and will get back to you after we debug a little more.

**Comment by kairos0ne** [comment]
I've been looking into this issue and it looks like its failing to upgrade to WebSocket: 

![image](https://user-images.githubusercontent.com/15980261/98475686-c3bf6c00-21ed-11eb-8e20-a5ddcc1e3b8a.png)


![image](https://user-images.githubusercontent.com/15980261/98475916-d5a10f00-21ed-11eb-8807-c02d1b5cdcf6.png)

**Comment by kairos0ne** [comment]
Looks like its forgery protection server side - I think this can be closed thanks.

**Comment by keduardo2117** [comment]
Hello, to anyone that is reading, do you know if this library works on Capacitor 6?
I have an app built in Nuxt 3 + Capacitor 6 and I'm sure I'm calling the cable.subscribe('channelName') method, but I never get a success or error message
