### ISSUE TITLE
unsubscribe on component destruction no longer works under Vue 2.x

### ISSUE THREAD

**Issue by elDub** [mclintprojects/actioncable-vue#40]
**Describe the bug**
When the [lifecycle hooks were modified](https://github.com/mclintprojects/actioncable-vue/commit/d1f2722f7f12d778de0fcef30a4c95d860fd3eb7) for Vue 3.x, channels are no longer unsubscribed on component destruction.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install under Vue 2.x with debugging fully on
2. Add a channel to a component that gets created and destroyed
3. Create component
4. Destroy component

**Expected behaviour**
The channel should get unsubscribed when the component is destroyed.

**Plugin version 2.4.1**

**Comment by mclintprojects** [comment]
@elDub Fixing this now.

**Comment by mclintprojects** [comment]
@elDub Fixed. Kindly update to v2.4.2
