### ISSUE TITLE
Object.entries is not a function

### ISSUE THREAD

**Issue by ilrock** [mclintprojects/actioncable-vue#41]
**Describe the bug**
For some users the library errors out throwing `Object.entries is not a function`. At first I thought this was an issue with IE as `Object.entries` does not work on IE, however, since plugging in AppSignal I've seen that the user agent is not matching IE.

**To Reproduce**
I wasn't able to reproduce the error on my own

**Expected behaviour**
No errors being thrown

**Screenshots**
![image](https://user-images.githubusercontent.com/4171627/110205774-4a254b00-7e7a-11eb-9598-2252c9b71e92.png)
![image](https://user-images.githubusercontent.com/4171627/110205784-590bfd80-7e7a-11eb-84bd-6113a9b7b0f2.png)

**Plugin version (please complete the following information): 2.3.2**

**Additional context**
Sorry for the lack of information so far - though I can add some context. This application is mostly used inside the Facebook webview. My (very rough) guess is that some version of the Facebook browser don't support `Object.entries` either.

Likely the error comes from this file [here](https://github.com/mclintprojects/actioncable-vue/blob/master/src/mixin.js) as `Object.entries` is used a couple of times.

I'd imagine that the solution would be to have a simple polyfill like [this](https://stackoverflow.com/a/47978439).

Happy to create a PR to get it fixed if you're too busy to do it.

**Comment by mclintprojects** [comment]
@ilrock Kindly create the PR. I'll review, merge and publish a new version.

**Comment by ilrock** [comment]
Thanks @mclintprojects!

Just created a [PR](https://github.com/mclintprojects/actioncable-vue/pull/42) - I haven't found any contribution guide so I hope the structure I used works for you.

If it doesn't let me know and I'll make the necessary changes.

**Comment by mclintprojects** [comment]
@ilrock Thanks for the PR. I've merged and published `v2.4.3`.
