### ISSUE TITLE
Can't get received to work

### ISSUE THREAD

**Issue by jnarowski** [mclintprojects/actioncable-vue#47]
First off, thanks for the awesome project! I cannot get data broadcasted from rails to show up on the Vue side no matter what I do!

**Describe the bug**
I am not seeing received show up in console. I've tried every combination. Sending a message works and the channel successfully connects.

channels/chat_channel.rb

```
class ChatChannel < ApplicationCable::Channel
  def subscribed
    stream_from 'ChatChannel'
  end

  def receive(data)
    p 'received....'
    puts data
  end
end
```

my vue file

```
<template>
  <div>
    <button @click="sendMessage">Send Message</button>
    <base-editor
      :show-toolbar="true"
      toolbar-class="bg-gray-200 flex px-4 py-3 sm:px-6 items-center"
      body-class="px-4 py-6 sm:px-6"
      class="full-height-editor"
    />
  </div>
</template>

<script>
export default {
  channels: {
    ChatChannel: {
      connected() {
        console.log('connected...')
      },
      rejected() {
        console.log('rejected...')
      },
      received(data) {
        console.log(data, 'abc...')
      },
      disconnected() {
        console.log('disconnected...')
      },
    },
  },
  mounted() {
    this.$cable.subscribe({
      channel: 'ChatChannel',
    })
  },
  methods: {
    sendMessage() {
      this.$cable.perform({
        channel: 'ChatChannel',
        data: {
          content: 'Message',
        },
      })
    },
  },
}
</script>

<style></style>
```

In the web console

```
connected...
actioncablevue.js?d567:1 Successfully connected to channel 'ChatChannel'.
```

To broadcast

```ActionCable.server.broadcast "ChatChannel", { message: '1234' }```

**To Reproduce**

I can send messages from vue to rails using sendMessage, but can't send anything from rails to vue?

In rails terminal when I load the browser:

```
08:55:16 web.1  | Finished "/cable/" [WebSocket] for 127.0.0.1 at 2021-03-25 08:55:16 -0600
08:55:16 web.1  | ChatChannel stopped streaming from ChatChannel
08:55:19 web.1  | Started GET "/cable" for 127.0.0.1 at 2021-03-25 08:55:19 -0600
08:55:19 web.1  | Started GET "/cable/" [WebSocket] for 127.0.0.1 at 2021-03-25 08:55:19 -0600
08:55:19 web.1  | Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
08:55:20 web.1  | ChatChannel is transmitting the subscription confirmation
08:55:20 web.1  | ChatChannel is streaming from ChatChannel
```

Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Plugin version (please complete the following information):**

**Additional context**

**Comment by pdxmeghan** [comment]
@jnarowski - Interesting. I just started using this last week and also did not get `#receive` to output anything from the Channel itself, but it did hit the `connected` in the Vue component. I had assumed then that perhaps `receive` wouldn't get hit, but I perhaps assumed wrongly. connect/connected both got hit for me, so it would be assumed that receive/received would also both get hit.

**Comment by mclintprojects** [comment]
Hey @jnarowski, @pdxmeghan I'm unable to reproduce this bug. Kindly confirm that your ActionCable server is configured correctly.

This is my ActionCable server code
```ruby
class TestChannel < ApplicationCable::Channel
  def subscribed
    stream_from "test_channel"
  end

  def send_message(data)
    ActionCable.server.broadcast("test_channel", response: "You sent: #{data["content"]}")
  end
end
```

And this is my JS code
```javascript
channels: {
  TestChannel: {
    connected(){
      this.$cable.perform({
        channel: 'TestChannel',
        action: 'send_message',
        data: {
          content: 'Hello',
        },
      });
    },
    received(data) {
      console.log(data);
    }
  }
},
created() {
  this.$cable.subscribe({ channel: 'TestChannel' });
}
```

And this is the result (received working correctly): https://share.getcloudapp.com/WnuYKdJD

**Comment by jnarowski** [comment]
I found out that action cable sends via some weird internal test for development. I changed the adapter to redis and it went through. Was a config error on my part, but def not obvious.

You might want to mention if you are using this library outside of rails, that you want to set your development cable adapter to redis.

development:
  adapter: redis
