### ISSUE TITLE
vue 3 - channel callback contexts are broken due to relying on vm._uid

### ISSUE THREAD

**Issue by tjk** [mclintprojects/actioncable-vue#49]
With multiple subscribed channels mounted at the same time, the contexts object (and other stuff) which relies on `context._uid` clashes which causes binding issues and maybe other things.

This seems to work as a stopgap, wasn't sure the best approach in the library to use...

```js
import { getCurrentInstance } from 'vue'
/* ... */
app.mixin({
  created() {
    this._uid = getCurrentInstance().uid
  },
})
```

**Comment by mclintprojects** [comment]
This is happening in Vue 3.x, yes? @tjk

**Comment by tjk** [comment]
Yes, discovered this when I worked on a vue 3 migration. We've since started using `@rails/actioncable` directly so I can't say whether this is still the case, sorry. Feel free to close! (although given someone hearted the issue there is a chance it is affecting others?)

**Comment by iuri-gg** [comment]
having same issue - vue3 with action cable subscribing multiple times in different components causing issue.

**Comment by phlegx** [comment]
Can confirm problem!

**Comment by iaacosta** [comment]
Can also confirm the problem happens in Vue 3

[This](https://github.com/mclintprojects/actioncable-vue/issues/61#issuecomment-1943836586) seems to work for me at the moment (thanks @tjk / @phlegx), you can also use `create()` but make sure the mixin is initialized **before** initializing the ActionCable plugin.

Haven't tried it in production yet, but if any confirmed related issues arise I'll be posting them here

**Comment by mclintprojects** [comment]
Fixed in `v3`
