### ISSUE TITLE
Dynamic channel names in Nuxt.js

### ISSUE THREAD

**Issue by nishihara-tm** [mclintprojects/actioncable-vue#6]
**Describe the bug**
Hello,

I've added actioncable-vue to my project. All is excellent! But one problem has just been up.
Subscribing to a channel with a dynamic name.

I'm currently using Nuxt.js with the version of 2.3.4 and here's the code I've written, which trying to use dynamic parameter with routes for channel ID

```
  data() {
    return {
       channelId: this.$route.params.id
    }
  }
  channels: {
    [this.channelId]: {
      connected() {},
      rejected() {},
      received(data) {
         console.log(data)
      },
      disconnected() {
      }
    }
  },

```
But they said this is not defined.
I tried with computed method either, but still didnt work
What do you think about this situation??
Thanks for you help!

Best,
Nishihara

**Comment by nishihara-tm** [comment]
Hi @mclintprojects !! Thank you for your reply!!
I tried as README says, but when I tried to run the code, they said window is not defined and I don't understand why.
```
 data() {
    return {
       channelId: 1
    }
  }
  channels: {
    [window.channelId]: {
      connected() {},
      rejected() {},
      received(data) {
         console.log(data)
      },
      disconnected() {
      }
    }
  },
```
If you have any good idea about how this might work, I would be really appreciated!

**Comment by mclintprojects** [comment]
@nishihara-tm I think the `window` global object does not exist in NuxtJS. Do you know what the equivalent of it is in NuxtJS?

**Comment by nishihara-tm** [comment]
@mclintprojects That's what I thought too.
Like you said, window global object does not exist in Nuxt JS.
Usually I managed to approach the problem with a solution like this, and works fine in most cases.
```
<script>
export default {
  mounted() {
    this.window = window
  },
}
</script>
```
But in this case, When I tried to use "this" inside of channel, "this" is not defined as well.
Therefore, I have no idea what to do about this......

**Comment by mclintprojects** [comment]
@nishihara-tm If there's no mutable global object in NuxtJS I don't think dynamic channels will work there. I'll try to do some more research. If you manage to find a fix before I do, kindly let me know.

**Comment by nishihara-tm** [comment]
@mclintprojects  Thank you for your kindness!

**Comment by mclintprojects** [comment]
Hi! @nishihara-tm. I just figured it out. It's a bit hacky but it works. `process` is global and mutable. Before you navigate to the page with the dynamic channel set the channelId with `process.global = {channelId: 5};`. You can use it later like `[process.global.channelId]: {}`.

Let me know how it goes.

**Comment by QuantumGeordie** [comment]
i don't think this is a Nuxt thing. more like trying to use the knife before it is made. i'm having a hard time getting a way to define the channel dynamically because no variables/values are available at the time the channels are defined (the window, process.global, etc.)

i do have the channel definitions in the same file/component as the subscriptions that happen at mount (at which point the dynamic channel name variables are fine/available).and i don't have a global data store like veux. 

is there something i am doing wrong? it feels like i am following the example code. are other folks using this feature?

**Comment by mclintprojects** [comment]
@QuantumGeordie I am currently thinking of a way to implement dynamic channels. If I figure it out, I'll update and let you guys know.

Also, yes, people are using the feature but it doesn't seem to be working for Nuxt.JS users.

What environment are you working in that doesn't have `window` or `process`?

**Comment by QuantumGeordie** [comment]
its not that it doesn't have `window` or `process`. it is that the values have not been set when it reads/evaluates/configures the channels definitions.

i can see in beforeCreate() or mounted() the correct values. but in
```
channels: {
        [window.channelId]: {
            connected() {},
            rejected() {},
            received(data) {},
            disconnected() {}
        }
    },
```
it has not been set yet.

**Comment by mclintprojects** [comment]
@nishihara-tm, @QuantumGeordie I have finally implemented support for channels with dynamic names. Kindly take a look at the README for how to go about using it.
