### ISSUE TITLE
Vue 2.6.12, Rails 6.02, subscribing loop

### ISSUE THREAD

**Issue by PatrykDubinski** [mclintprojects/actioncable-vue#62]
Hello

I'm using Vue 2.6.12 with Rails 6.02 and when i try to subscribe to ActionCable all i get is "welcome message" and then it starts subscribing loop and keeps connecting and disconnecting from websocket. After couple of minutes there are many "/cable" finished request instead of couple listening/pending. This bug happens on actioncable-vue@2.5.1 but i figured that it's working on version 2.4.6.

**To Reproduce**
Steps to reproduce the behaviour:

1. Generate channel in rails action cable and remove generated js channel
2. Configure ActionCable authorization and subscribing just to not throw an "Unauthorized" error
3. Subscribe to Channel with actioncable-vue
4. When websocket will try to connect in Network tab there will be multiple requests and subscribing loop

**Screenshots**
Screenshot below. Every "cable" request looks the same
![Zrzut ekranu 2022-01-11 o 07 54 51](https://user-images.githubusercontent.com/71813865/148895391-55fde05c-43b4-4f73-bfeb-3b925a0e7d3a.png)

**Comment by mammad2c** [comment]
Hi,
can you provide your codes to detect what happens exactly?

**Comment by mclintprojects** [comment]
I can't seem to reproduce this. Closing this issue for now.
