### ISSUE TITLE
Send Headers on Connection

### ISSUE THREAD

**Issue by rafaeliga** [mclintprojects/actioncable-vue#73]
Hello there,

When connecting my flutter app to rails, Im sending headers to authorize:

```dart
cable = ActionCable.Connect(constants.socketHost, headers: {
        "Authorization": constants.socketToken,
      }, onConnected: () {
```

Is there a way to do the same with actioncable-vue?

Thanks,

**Comment by rafaeliga** [comment]
Any ideas?

Make sense if I create this issue on rails/actioncable?

**Comment by jakob-lilliemarck** [comment]
I've run into the same issue. Passing authentication tokens in the url as the docs propose is widely insecure and bad practice. Apparently passing headers on the initial http upgrade request is unsupported in browsers:
[](https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api)

I guess the next best option is to send the token over the websocket channel after connection, and then start streaming the data that requires auth.

**Comment by mclintprojects** [comment]
@rafaeliga Like @jakob-lilliemarck said the best way to do this is to pass the token as a query parameter in the connection URL. e.g `http://localhost:3000/cable?token=XYZ`
